/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */

public class calcuLadora extends javax.swing.JFrame {

    /**
     * Creates new form calcuLadora
     */
    public calcuLadora() {
        initComponents();
    }
int n,d;
float dIv;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        diV = new javax.swing.JButton();
        veZes = new javax.swing.JButton();
        meNos = new javax.swing.JButton();
        maIs = new javax.swing.JButton();
        re1S = new javax.swing.JTextField();
        re2S = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel1.setText("Calculadora Simples");

        diV.setText("/");
        diV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diVActionPerformed(evt);
            }
        });

        veZes.setText("*");
        veZes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veZesActionPerformed(evt);
            }
        });

        meNos.setText("-");
        meNos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meNosActionPerformed(evt);
            }
        });

        maIs.setText("+");
        maIs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maIsActionPerformed(evt);
            }
        });

        re1S.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        re1S.setToolTipText("");
        re1S.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        re1S.setName(""); // NOI18N
        re1S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re1SActionPerformed(evt);
            }
        });

        re2S.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        re2S.setToolTipText("");
        re2S.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        re2S.setName(""); // NOI18N
        re2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re2SActionPerformed(evt);
            }
        });

        jLabel2.setText("Numerador");

        jLabel3.setText("Denominador");

        reS.setText("Resposta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(re1S, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(re2S, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(diV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(veZes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(meNos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maIs))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(reS)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re1S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(re2S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diV)
                    .addComponent(veZes)
                    .addComponent(meNos)
                    .addComponent(maIs))
                .addGap(48, 48, 48)
                .addComponent(reS)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void diVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diVActionPerformed
        // TODO add your handling code here:
        n = Integer.parseInt(re1S.getText());
        d = Integer.parseInt(re2S.getText());
        dIv=n/d;
        reS.setText(Float.toString(dIv));
    }//GEN-LAST:event_diVActionPerformed

    private void veZesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veZesActionPerformed
        // TODO add your handling code here:
        n = Integer.parseInt(re1S.getText());
        d = Integer.parseInt(re2S.getText());
        dIv=n*d;
       reS.setText(Float.toString(dIv));
    }//GEN-LAST:event_veZesActionPerformed

    private void re1SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re1SActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_re1SActionPerformed

    private void re2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re2SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re2SActionPerformed

    private void meNosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meNosActionPerformed
        // TODO add your handling code here:
        n = Integer.parseInt(re1S.getText());
        d = Integer.parseInt(re2S.getText());
        dIv=n-d;
        reS.setText(Float.toString(dIv));
    }//GEN-LAST:event_meNosActionPerformed

    private void maIsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maIsActionPerformed
        // TODO add your handling code here:
        n = Integer.parseInt(re1S.getText());
        d = Integer.parseInt(re2S.getText());
        dIv=n+d;
       reS.setText(Float.toString(dIv));
    }//GEN-LAST:event_maIsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcuLadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcuLadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcuLadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcuLadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcuLadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton maIs;
    private javax.swing.JButton meNos;
    private javax.swing.JTextField re1S;
    private javax.swing.JTextField re2S;
    private javax.swing.JLabel reS;
    private javax.swing.JButton veZes;
    // End of variables declaration//GEN-END:variables
}
